[package]
name = "linux-rawgadget-usbd"
version = "0.1.0"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
usb-device = "0.2.5"
nix = "0.17.0"
libusb-sys = "0.2.3"
